<p>Exceptions in C++ don't need to be caught (no compile time errors) by the calling function. So it's up to developer's judgment whether to catch them using try/catch (unlike in Java).</p>

<p>Is there a way one can ensure that the exceptions thrown are always caught using try/catch by the calling function?</p>
